### ISSUE TITLE
scaleLinear returns range instead of number

### ISSUE THREAD

**Issue by seanhoughton** [iamssen/typings-d3#4]
The scaleLinear() function in the d3-scale typings returns a Linear<Range>instead of a number. Is this intentional? I'm having to cast the return value to <number> to get things working in my code. I'm not a d3 expert, but I believe the scale functions are intended to return numerical values.

Thanks for the type declarations!

**Comment by iamssen** [comment]
Hi. @seanhoughton 
Sorry. my english is not good. I don't know my understanding is exactly for your question.

scaleLinear() function return `Linear<Range>` instance. (it can not return a number)
(scaleLinear() is a factory function. it create a `Linear` instance.)

- <https://github.com/iamssen/typings-d3/blob/master/tests/d3-scale.js#L4>
- <https://github.com/d3/d3-scale#_continuous>
